# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='equipment',
        ),
        migrations.AddField(
            model_name='feature',
            name='equipments',
            field=models.ManyToManyField(to='equipment.Equipment'),
        ),
    ]
