# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_auto_20170918_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='is_tested',
            field=models.BooleanField(default=False),
        ),
    ]
