# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='docString',
            field=models.CharField(default='test', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipment',
            name='tag',
            field=models.CharField(default='JP400', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipment',
            name='tfmPrefix',
            field=models.CharField(default='-', max_length=10),
            preserve_default=False,
        ),
    ]
